const questions = [
  {q:"Personaje que encabezó el Segundo Imperio en el México independiente:",o:["Antonio López de Santa Anna.","Fernando Maximiliano de Habsburgo.","Agustín de Iturbide.","Lucas Alamán."],a:1},
  {q:"El artífice de las primeras reformas liberales llevadas a cabo en 1833 fue:",o:["Lucas Alamán.","Valentín Gómez Farías.","Benito Juárez.","Antonio López de Santa Anna."],a:1},
  {q:"Documento por el que se acepta la renuncia de Porfirio Díaz, lo cual marca el triunfo del movimiento maderista:",o:["Plan de la Noria.","Plan de San Luis.","Plan de Ayala.","Tratados de Ciudad Juárez."],a:3},
  {q:"En 1929 se dio inicio a la “revolución institucionalizada” con la creación de:",o:["Partido Revolucionario Institucional (PRI).","Partido de la Revolución Mexicana (PRM).","Partido Nacional Revolucionario (PNR).","La Confederación de Trabajadores Mexicanos (CTM) y la Confederación Nacional de Organizaciones Populares (CNOP)."],a:2},
  {q:"Al período histórico que corre entre 1929 y 1935, durante el cual Plutarco Elías Calles gozó de gran influencia, se le conoce como:",o:["Plutarquismo.","Maximato.","Generalato.","Caudillismo."],a:1},
  {q:"Entre 1958 y 1970 la economía mexicana creció a altas tasas con baja inflación, por lo que a dicho período se le conoce como:",o:["Desarrollo exportador.","Desarrollo estabilizador.","Crecimiento milagroso.","Era de oro."],a:1},
  {q:"Evento que marca simbólicamente el inicio de la actividad guerrillera en los años sesenta:",o:["Quema del cuartel de Ciudad Madera, Chihuahua.","El Halconazo.","Asesinato de Eugenio Garza Sada.","Toma de la rectoría de Ciudad Universitaria."],a:0},
  {q:"La adhesión de México al Acuerdo General sobre Aranceles Aduaneros y Comercio (GATT, por sus siglas en inglés) se produjo en el año:",o:["1979.","1982.","1986.","1990."],a:2},
  {q:"Presidente de México que llevó a cabo la nacionalización de la banca:",o:["Luis Echeverría Álvarez.","José López Portillo.","Miguel de la Madrid Hurtado.","Carlos Salinas de Gortari."],a:1},
  {q:"Los estados de Coahuila, Nuevo León, Tamaulipas y Chihuahua hacen frontera con:",o:["California.","Nuevo México.","Texas.","Arizona."],a:2},
  {q:"La mayor parte de la población ocupada del país, de acuerdo con el INEGI, gana:",o:["Entre uno y dos salarios mínimos mensuales.","Entre dos y cinco salarios mínimos mensuales.","Más de cinco salarios mínimos mensuales.","Hasta un salario mínimo mensual."],a:1},
  {q:"Las siguientes entidades federativas se localizan en la zona conocida como “El Bajío”, EXCEPTO:",o:["Guanajuato.","Sinaloa.","Aguascalientes.","Querétaro."],a:1},
  {q:"Países con los cuales colinda México en su frontera sur:",o:["Belice y Guatemala.","Belice, Guatemala y Honduras.","Belice, Guatemala y El Salvador.","Guatemala y Honduras."],a:0},
  {q:"La superficie territorial de México es:",o:["1,105,400 km².","1,964,375 km².","2,867,899 km².","3,502,988 km²."],a:1},
  {q:"La edad promedio de la población de México es:",o:["46 años.","33 años.","20 años.","27 años."],a:3},
  {q:"De acuerdo con la Convención de Viena sobre Relaciones Consulares, el Estado receptor debe otorgar su consentimiento para:",o:["Permitir la instalación o el cambio de sede de una oficina consular.","Declarar a una persona como non grata.","Que la oficina consular proteja los intereses de su Estado.","Representar a los nacionales del Estado que envía o tomar las medidas convenientes para su representación ante los tribunales."],a:0},
  {q:"De acuerdo con el artículo 12 de la Convención de Viena sobre Relaciones Consulares, el exequátur es una autorización otorgada por:",o:["El poder legislativo de un Estado que envía a un representante a otro país.","La Secretaría de la Función Pública.","El Estado receptor de una oficina consular de otro país.","El poder ejecutivo de un país que envía una solicitud de oficina consular a otro país."],a:2},
  {q:"De acuerdo con el artículo 49 constitucional, el Supremo Poder de la Federación se divide para su ejercicio en:",o:["Ejecutivo, Legislativo y Electoral.","Ejecutivo, Legislativo y Judicial.","Ejecutivo, Diputados y Judicial.","Ejecutivo, Legislativo y Policial."],a:1},
  {q:"De acuerdo con el artículo 40 constitucional, la República mexicana es:",o:["Representativa, democrática, laica y federal.","Representativa, democrática y federal.","Participativa, democrática, laica y federal.","Representativa, democrática, laica y municipalista."],a:0},
  {q:"De acuerdo con la Ley de Adquisiciones, Arrendamientos y Servicios del Sector Público, los procesos de contratación del sector público pueden utilizar tres procedimientos:",o:["Compranet, licitación pública y adjudicación directa.","Licitación pública, adjudicación directa y concurso.","Licitación pública, invitación a cuando menos tres personas y adquisición electrónica.","Adjudicación directa, invitación a cuando menos tres personas y licitación pública."],a:3},
  {q:"De acuerdo con la Ley Federal de Archivos, cada sujeto obligado deberá nombrar a los responsables de los archivos:",o:["De trámite, de concentración e histórico.","En tránsito, de concentración e histórico.","Administrativo, histórico y de clasificación.","Privado, de concentración y de trámite."],a:0},
  {q:"De acuerdo con la Ley Federal de Presupuesto y Responsabilidad Hacendaria, los siguientes tres elementos son fundamentales para la presupuestación y programación anual del gasto público:",o:["Las políticas del Plan Nacional de Desarrollo, el Índice Nacional de Precios al Consumidor y los programas sectoriales.","Las políticas del Plan Nacional de Desarrollo, los programas sectoriales y el marco macroeconómico de mediano plazo de acuerdo con los criterios generales de política económica.","Los programas sectoriales, el Fondo de Estabilización de los Ingresos Presupuestarios y el precio del petróleo.","El Plan Nacional de Desarrollo, el Fondo de Estabilización de los Ingresos Presupuestarios y el Fondo de Estabilización de los Ingresos de las Entidades Federativas."],a:1},
  {q:"De acuerdo con la Ley General de Transparencia y Acceso a la Información Pública, la página de inicio de los portales de Internet de un sujeto obligado deberá contener como mínimo:",o:["Un vínculo a la Ley de Transparencia y Acceso a la Información Pública, así como a las demás leyes del sector público.","Un vínculo al presupuesto del sujeto obligado y a sus registros históricos.","Un vínculo de acceso directo al sitio donde se encuentra la información pública, el cual deberá contar con un buscador.","Una pantalla de advertencia sobre la veda de información en periodos electorales, así como su fecha de inicio y término."],a:2},
  {q:"De acuerdo con la Ley General de Contabilidad Gubernamental, la compatibilización de los modelos contables vigentes a nivel nacional se conoce como:",o:["Armonización.","Gasto comprometido.","Catálogo de cuentas.","Contabilidad gubernamental."],a:0},
  {q:"De acuerdo con la Ley Orgánica de la Administración Pública Federal, son entidades de la Administración Pública Federal paraestatal:",o:["Las Secretarías de Estado, las empresas de participación estatal y los fideicomisos.","Las empresas paraestatales, los fideicomisos y los organismos desconcentrados.","Los organismos desconcentrados, las empresas de participación estatal y los fideicomisos.","Los organismos descentralizados, las empresas de participación estatal y los fideicomisos."],a:3},
  {q:"De acuerdo con la Ley del Servicio Exterior Mexicano, la representación del Estado mexicano ante organismos internacionales recibe el nombre de:",o:["Oficina consular.","Delegación diplomática.","Misión diplomática.","Misión permanente."],a:3},
  {q:"¿A cuál de los siguientes ordenamientos le corresponde fijar los asuntos que debe despachar la Secretaría de Relaciones Exteriores?",o:["Ley del Servicio Exterior Mexicano.","Ley Orgánica de la Administración Pública Federal.","Manual de Organización General de la Secretaría de Relaciones Exteriores.","Reglamento Interior de la Secretaría de Relaciones Exteriores."],a:1},
  {q:"Es una prioridad internacional de acuerdo con el Programa Sectorial de Relaciones Exteriores 2013-2018:",o:["Introducir sistemas informáticos en la Secretaría de Relaciones Exteriores.","Fortalecer los presupuestos de las embajadas y consulados.","Promover a México como un destino atractivo tanto para las inversiones como para los visitantes.","Participar en el Consejo de Seguridad de la ONU."],a:2},
  {q:"Es una de las estrategias transversales del Plan Nacional de Desarrollo 2013-2018:",o:["Impulsar la proyección internacional del país para alcanzar un México Global.","Introducir la perspectiva de género en todas las acciones de gobierno.","Generar igualdad de oportunidades para un México Próspero.","Desarrollar el capital humano para un México con Educación de Calidad."],a:1},
  {q:"El Reglamento de Pasaportes y del Documento de Identidad y Viaje permite que se tengan dos pasaportes mexicanos sólo en caso de:",o:["Que se obtenga la autorización de una Secretaría de Estado.","Que se tenga uno diplomático y uno oficial.","Que se tenga uno diplomático u oficial y uno ordinario.","Bajo ninguna circunstancia se permite tener dos pasaportes válidos."],a:2},
  {q:"De acuerdo con la Ley Federal de Responsabilidades de los Servidores Públicos, el periodo máximo de inhabilitación que se le puede imponer a un servidor público debido a faltas administrativas es de:",o:["5 años.","10 años.","15 años.","20 años."],a:3},
  {q:"De acuerdo con la Ley General de Contabilidad Gubernamental, los tres criterios sustantivos de los estados financieros y la información emanada de la contabilidad son:",o:["Confiabilidad, relevancia y comparación.","Eficiencia, eficacia y economía.","Equidad, comparabilidad e integralidad.","Confiabilidad, eficacia y efectividad."],a:0},
  {q:"De acuerdo con la Ley de Firma Electrónica Avanzada, el principio rector llamado “no repudio” de una firma electrónica avanzada significa que:",o:["Se garantiza que el documento sólo pueda ser cifrado por el firmante y el receptor.","Se garantiza la autoría e integridad del documento y que dicha firma corresponde exclusivamente al firmante.","Se garantiza que los datos han permanecido completos e inalterados desde su firma, con independencia de los cambios que hubiere podido sufrir el medio que lo contiene como resultado del proceso de comunicación, archivo o presentación.","Se satisface el requisito de firma del mismo modo que la firma autógrafa en los documentos impresos."],a:1},
  {q:"De acuerdo con la Ley de Adquisiciones, Arrendamientos y Servicios del Sector Público, los extranjeros pueden participar en las licitaciones gubernamentales, en su modalidad de licitación internacional, cuando:",o:["Lo autoriza la Secretaría de Relaciones Exteriores.","Lo autoriza la Organización Mundial de Comercio.","Se tenga celebrado un tratado de libre comercio con capítulo de compras gubernamentales con sus países.","Se tenga celebrado un convenio entre el país extranjero y la entidad o dependencia gubernamental."],a:2},
  {q:"De acuerdo con la Ley Federal de Responsabilidades de los Servidores Públicos, cuando un servidor público identifique hechos que, a su juicio, sean causa de responsabilidad administrativa imputables a servidores públicos sujetos a su dirección, deberá denunciar ante:",o:["El Ministerio Público.","La contraloría interna de su dependencia o entidad.","El titular de la dependencia o entidad.","Su jefe inmediato."],a:1},
  {q:"De acuerdo con la Ley General de Transparencia y Acceso a la Información Pública Gubernamental, dentro de las obligaciones de “transparencia comunes” para los sujetos obligados están:",o:["Los documentos clasificados de la entidad o dependencia.","Las bases de datos personales a disposición del sujeto obligado.","Las noticias periodísticas más importantes para el público.","Los indicadores relacionados con temas de interés público o trascendencia social que, conforme a sus funciones, deban establecer los sujetos obligados."],a:3},
  {q:"De acuerdo con la Ley Orgánica de la Administración Pública Federal, los manuales de organización general de una dependencia deben ser publicados en:",o:["Periódicos de circulación nacional.","Diario Oficial de la Federación.","Reportes de trabajo.","Blogs de dominio público."],a:1},
  {q:"Desde la perspectiva del desarrollo organizacional y la planeación estratégica, los cuatro niveles de objetivos de acuerdo a la metodología del marco lógico son:",o:["Fines, propósitos, componentes y actividades.","Fines, objetivos, metas y actividades.","Misión, visión, objetivos estratégicos y objetivos de proyecto.","Fines, misión, visión y objetivos."],a:0},
  {q:"El árbol de problemas de la metodología del marco lógico se compone de la suma de los siguientes árboles:",o:["De síntomas, de causas y de soluciones.","De causas y de efectos.","De actividades, componentes, propósito y fin.","De soluciones y síntomas."],a:1},
  {q:"En la metodología del marco lógico, la principal diferencia entre componente y actividad es que el:",o:["Componente es lo que se entrega en la ejecución y actividad lo que se realiza para ejecutar.","Componente es lo que se realiza y actividad lo que se entrega.","Componente es el elemento que se necesita para actuar y actividad lo que se diagnostica.","Componente es lo que se entrega en la ejecución y actividad la suma de los indicadores de impacto."],a:0},
  {q:"En la planeación estratégica, se le conoce como misión y visión a:",o:["La definición de resultados y del plan de acción.","La razón de ser y al futuro deseado de la organización o entidad.","Los indicadores y a las amenazas y oportunidades.","Las amenazas, oportunidades, debilidades y fortalezas de la entidad u organización."],a:1},
  {q:"En la planeación estratégica las restricciones al logro de la misión se les conoce como FODA, que significa:",o:["Fortalezas, oportunidades, desviaciones y amenazas.","Fuerzas, oportunidades, debilidades y acciones.","Fallas, omisiones, debilidades y amenazas.","Fortalezas, oportunidades, debilidades y amenazas."],a:3},
  {q:"La diferencia entre objetivos estratégicos y estrategia es la misma que entre:",o:["Los resultados que se espera lograr y el plan de acción para realizarlos.","Las metas específicas definidas y los indicadores medidos.","Los resultados alcanzados y los esperados.","El FODA y la misión y visión."],a:0},
  {q:"En planeación estratégica, cuando se habla de indicadores, la diferencia entre indicadores de “producto” e indicadores de “resultado” es que:",o:["Los indicadores de producto se refieren a la economía y los de resultado a la eficiencia.","Los indicadores de producto son claros y los indicadores de resultado son ambiguos.","Los indicadores de producto muestran los servicios y productos y los indicadores de resultado muestran los impactos.","Los indicadores de producto son de cobertura y los indicadores de resultado son de “focalización”."],a:2},
  {q:"La principal diferencia entre los indicadores de eficiencia y los de eficacia es que:",o:["Los de eficiencia se preocupan de la cobertura y los de eficacia de la “focalización”.","Los de eficiencia se ocupan tanto de los insumos como de los productos generados y los de eficacia del logro de los objetivos.","Los de eficiencia son para organizaciones económicas y los de eficacia para organizaciones políticas.","Los de eficiencia son cuantitativos y los de eficacia son cualitativos."],a:1},
  {q:"Dentro de las teorías del cambio organizacional, una de las más conocidas es el llamado “movimiento de la calidad”, cuyo énfasis principal está en:",o:["Los factores psicosociales del cambio.","El ciclo de vida de la organización.","Que la organización debe dirigirse a la satisfacción de los clientes a través de los servicios o productos que otorga.","La eficiencia de la organización en términos financieros."],a:2},
  {q:"Son elementos fundamentales de la definición de gobernanza según la OCDE:",o:["Los acuerdos formales e informales que determinan cómo se toman las decisiones públicas.","La gobernabilidad entre partidos.","Los gobiernos estatales y municipales.","Los planes nacionales de desarrollo."],a:0},
  {q:"En 2010 se inició en el gobierno federal la llamada “tala regulatoria”, la cual consistió en:",o:["Reducir el uso de papel en las oficinas públicas para reducir la tala de árboles.","Regular los espacios dirigidos a la conservación del medio ambiente.","Aumentar la capacidad de los trámites gubernamentales.","Reducir las regulaciones que el gobierno federal impone a los ciudadanos a través de trámites y permisos."],a:3},
  {q:"El Servicio Profesional de Carrera en el gobierno federal en México, de acuerdo con la OCDE, involucra a:",o:["Personal de base y de confianza de la Administración Pública Federal.","Todo el personal de la Administración Pública Federal.","Cierto personal de confianza de la Administración Pública Federal.","Personal sindicalizado de la Administración Pública Federal."],a:2},
  {q:"La subcontratación en el modelo de la “nueva administración pública” se refiere a:",o:["Contratar a proveedores privados para realizar labores gubernamentales.","Devolver facultades a los gobiernos locales.","Contrataciones públicas a precios por debajo del mercado.","Privatizar empresas públicas."],a:0},
  {q:"En política pública la definición de la agenda gubernamental es:",o:["El proceso a través del cual se definen los problemas públicos a enfrentar y atender.","La agenda pública del titular del Ejecutivo.","La coordinación de actividades entre las diferentes secretarías y entidades del gobierno.","La agenda de cooperación internacional de un gobierno."],a:0},
  {q:"La “burocracia al nivel de la calle” se refiere a:",o:["Los bajos sueldos de la burocracia en diferentes países.","Los trabajadores del Estado que están en contacto directo con los ciudadanos.","Los trámites que la gente debe realizar en las oficinas públicas.","Las oficinas de trámites privados o públicos."],a:1},
  {q:"El modelo de políticas públicas de “arriba hacia abajo” se refiere a:",o:["Que las políticas públicas las desarrolla la élite gobernante.","Una política pública que comienza en la ley, pues ésta autoriza los actos de gobierno.","Una política pública que se apoya básicamente en argumentos técnicos.","Que las políticas públicas inician en las discusiones de los grupos y las comunidades."],a:1},
  {q:"La etapa de la política pública en la que se involucra una serie de agencias ejecutoras y administradoras es:",o:["Implementación.","Definición de la agenda.","Evaluación.","Formulación."],a:0},
  {q:"De acuerdo con la OCDE, las estrategias de gobierno electrónico pueden mejorar la confianza de la gente en su gobierno porque:",o:["Se hacen más rápidas las transacciones.","Los ciudadanos participan en las políticas públicas.","Se reduce el presupuesto que hay que gastar en los trámites gubernamentales.","Se incrementa la información técnica disponible para los tomadores de decisión."],a:1},
  {q:"Uno de los problemas potenciales de los enfoques de política pública “de abajo hacia arriba” es que se:",o:["Reduce la cantidad de información disponible para tomar decisiones.","Reduce la participación de ciudadanos y grupos sociales.","Obstaculiza la participación de las organizaciones civiles en las decisiones.","Pueden obstaculizar políticas gubernamentales ya establecidas."],a:3},
  {q:"De acuerdo con los artículos 25 y 26 de la Constitución Política de los Estados Unidos Mexicanos, el Estado es responsable del desarrollo económico de la nación a través de:",o:["Organizar a los poderes Ejecutivo, Legislativo y Judicial.","Planear, coordinar y orientar la actividad económica.","Definir las políticas de la banca privada.","Impulsar la migración."],a:1},
  {q:"Las tres grandes categorías organizativas en que se divide el sector público mexicano son:",o:["Ejecutivo, legislativo y judicial.","Sector central, sector paraestatal y la Secretaría de Relaciones Exteriores.","Sector central, sector paraestatal y sector público financiero.","Social, militar e industrial."],a:2},
  {q:"Es una definición aceptada de gasto público:",o:["Gasto realizado por los departamentos gubernamentales en bienes y servicios o a través de subsidios.","Gasto en pagos de deuda interna más deuda externa.","Cobro de impuestos a los ciudadanos.","Consumo del gobierno en TICs."],a:0},
  {q:"Indique cuál de las siguientes opciones es la correcta de acuerdo con la clasificación por Objeto del Gasto de la Administración Pública Federal:",o:["El capítulo 1000 corresponde al gasto por concepto de “obras públicas”.","El capítulo 2000 corresponde al gasto por concepto de “materiales y suministros”.","El capítulo 3000 corresponde al gasto por concepto de “servicios personales”.","El capítulo 7000 corresponde al gasto por concepto de “bienes muebles, inmuebles e intangibles”."],a:1},
  {q:"El gasto programable es aquel:",o:["Financiado deficitariamente.","Que se destina a pago de deuda.","No recurrente.","Que tiene efectos directos en la actividad económica, social y de generación de empleos."],a:3},
  {q:"Que el proceso presupuestal deba seguir los principios de “equilibrio y unidad” significa que:",o:["El presupuesto debe abarcar toda la actividad financiera del Estado y que debe hacerse con gran exactitud.","El presupuesto debe existir con equilibrio de ingresos y gastos y que debe haber un solo fondo de ingresos y gastos.","Que el presupuesto debe ser claro y que debe detallarse los elementos de gasto e ingreso que lo integran.","Que el presupuesto debe considerar la deuda y que todos los actores estén de acuerdo."],a:1},
  {q:"La técnica presupuestal que exige a las unidades administrativas una justificación detallada de sus gastos anuales sin importar lo que hayan hecho en el pasado es el:",o:["Presupuesto tradicional.","Presupuesto por programas.","Presupuesto por objetos específicos de gasto.","Presupuesto base cero."],a:3},
  {q:"El documento jurídico, financiero y de política económica y social que es aprobado mediante decreto por la Cámara de Diputados a iniciativa del Ejecutivo Federal es:",o:["El proceso presupuestario.","La Ley de Contabilidad Gubernamental.","El Presupuesto de Egresos de la Federación.","La Ley de Presupuesto."],a:2},
  {q:"Son etapas del proceso de presupuesto que se encargan de vigilar y verificar el gasto de los recursos y de valorar los resultados que se obtuvieron con el ejercicio:",o:["Control y evaluación.","Control y aprobación.","Formulación y ejercicio.","Aprobación y evaluación."],a:0},
  {q:"Las Normas Internacionales de Información Financiera (NIIF) son:",o:["Normas creadas por el Estado mexicano en la Ley General de Contabilidad Gubernamental.","Normas internacionales para la formulación de presupuestos públicos.","Normas internacionales para el control del gasto.","Normas o leyes internacionales que regulan la información que debe presentarse en los estados financieros."],a:3},
  {q:"Uno de los objetivos del Marco Conceptual de Contabilidad Gubernamental (MCCG) es:",o:["Proporcionar los conceptos imprescindibles que rigen a la contabilidad gubernamental, identificando de manera precisa las bases que la sustentan.","Generar un marco para la relación contable entre empresas privadas y públicas.","Definir el Presupuesto de Egresos de la Federación.","Incorporar criterios financieros a los estados contables de las empresas."],a:0},
  {q:"El órgano de coordinación para la armonización de la contabilidad gubernamental es:",o:["La Auditoría Superior de la Federación.","La Secretaría de Hacienda y Crédito Público.","El Consejo Nacional de Armonización Contable (CONAC).","El Centro de Estudios de Finanzas Públicas (CEFP)."],a:2},
  {q:"Algunos sujetos que deben observar obligatoriamente la Ley General de Contabilidad Gubernamental son:",o:["Empresas privadas de estados y municipios.","Organismos internacionales en el país.","Embajadas y consulados extranjeros en México.","Ayuntamientos y Poderes Judicial y Legislativo."],a:3},
  {q:"Los tipos de información que el sector público genera de acuerdo con la Ley General de Contabilidad Gubernamental son:",o:["Contable, presupuestaria y programática.","Transparencia focalizada, obligaciones y estructura de la dependencia o entidad.","Estados financieros.","Sanciones de acuerdo con la Ley de Responsabilidades Administrativas."],a:0},
  {q:"El “riesgo país” se define como:",o:["La tasa de victimización de un país.","La prima de riesgo que exigen los inversionistas en el mercado ante la posibilidad de un default o suspensión de pagos de su deuda.","La prima de riesgo que el Banco de México define para un deudor.","El riesgo de que el Banco Central de un país aumente su tasa de interés."],a:1},
  {q:"Una forma de medir la tasa de recaudación de un país es:",o:["La tasa del impuesto al valor agregado.","La tasa del impuesto a la renta más los impuestos financieros.","El porcentaje de los impuestos cobrados respecto del PIB.","El porcentaje de los impuestos sobre la renta respecto de los impuestos al consumo."],a:1},
  {q:"Un impuesto es regresivo es aquel que:",o:["Carga más impuestos proporcionalmente a quienes más tienen.","Una vez cobrado no es posible deducirlo.","Carga más impuestos proporcionalmente a quienes menos tienen.","Se le retorna al contribuyente como deducciones."],a:2},
  {q:"Un gasto redistributivo es aquel que:",o:["Busca distribuir las cargas de gasto entre los diferentes programas.","Distribuye de maneras innovadoras el gasto de acuerdo a necesidades sociales.","Cambia de distribución con el tiempo.","Pretende impactar más en la población que tiene más necesidades."],a:3},
  {q:"Son ejemplos de impuestos al ingreso y al consumo, respectivamente:",o:["Impuestos especiales e impuestos a capitales.","Impuestos a transacciones financieras e Impuesto sobre la Renta (ISR).","Impuesto sobre la Renta (ISR) e Impuesto al Valor Agregado (IVA).","Impuesto al Valor Agregado (IVA) e Impuesto sobre la Renta (ISR)."],a:2},
  {q:"El gasto que utiliza el Estado para cumplir con su funcionamiento normal es el:",o:["Gasto de capital.","Gasto en servicios personales.","Gasto corriente.","Gasto fiscal."],a:2},
  {q:"Una diferencia crítica entre presupuestos tradicionales y presupuestos por programas es que:",o:["El presupuesto por programas parte de una definición explícita de objetivos y metas en las partidas.","El ciclo presupuestario es más largo en el primero.","El presupuesto tradicional requiere comenzar de cero.","El presupuesto por programas está basado en ley."],a:0},
  {q:"Circunstancias en las que se expide un certificado de presunción de nacionalidad en el extranjero:",o:["Mexicano o extranjero con acta de nacimiento.","Extranjero para ingresar a territorio nacional.","Mexicano que carece de documentos de identidad y nacionalidad.","Mexicano indigente con pasaporte."],a:2},
  {q:"El certificado de matrícula consular es una ______ que expide una representación consular a favor de un ______ para hacer constar que ______.",o:["Credencial, residente, está en la ciudad.","Certificación, ciudadano, trabaja en esa circunscripción.","Identificación, connacional, está domiciliado en esa circunscripción.","Tarjeta, paisano, es mexicano."],a:2},
  {q:"El consulado móvil realiza las siguientes funciones:",o:["Participa en eventos de las comunidades mexicanas.","Presta servicios de asesoría y orientación a mexicanos y extranjeros.","Mueve la oficina consular fuera de la circunscripción.","Presta servicios a mexicanos fuera de la oficina consular dentro de la circunscripción."],a:3},
  {q:"Principales funciones del Instituto de los Mexicanos en el Exterior (IME):",o:["Prevenir la pérdida de la nacionalidad entre la comunidad mexicana que radica en el extranjero.","Atender las iniciativas y necesidades comunitarias de los mexicanos que viven y trabajan fuera de México.","Tramitar documentación consular y migratoria.","Proveer asistencia legal a mexicanos, especialmente a aquellos que se encuentran condenados a pena de muerte."],a:1},
  {q:"Programas y servicios que ofrece el IME:",o:["Pasaportes, certificados de matrícula consular, registro de nacimientos, cartillas del servicio militar.","Programas de salud, deportes, cultura, educación, remesas.","Poderes notariales, certificados, compulsas, inclusión financiera.","Actas de defunción, traslado de restos, apostillas, visas."],a:1},
  {q:"¿Cuál es la legislación vigente para documentar a extranjeros para su ingreso a territorio nacional?",o:["Ley General de Población y Código Penal Federal.","Ley de Migración, su Reglamento y demás lineamientos administrativos y acuerdos bilaterales en la materia.","Código Civil Federal y su Reglamento.","Ley de Nacionalidad y su Reglamento."],a:1},
  {q:"El Sistema Integral de Administración Consular (SIAC) consiste en una aplicación informática mediante la cual:",o:["Se ingresan insumos para generar un expediente de protección a un connacional en las representaciones diplomáticas y consulares de México en el exterior.","Se expiden todos los servicios consulares en las representaciones diplomáticas y consulares de México en el exterior.","Se registran los gastos y las operaciones en materia de documentación consular en las representaciones diplomáticas y consulares de México en el exterior.","Se consultan los datos de los connacionales que residen en las respectivas adscripciones de las representaciones diplomáticas y consulares de México en el exterior."],a:1},
  {q:"El Certificado de Matrícula Consular tiene una vigencia de:",o:["2 años.","3 años.","5 años.","10 años."],a:2},
  {q:"Artículos de la Constitución Política de los Estados Unidos Mexicanos que se reformaron para introducir la no pérdida de nacionalidad:",o:["Artículos 3, 34, 27.","Artículos 1, 36, 78.","Artículos 33, 35, 89.","Artículos 30, 32, 37."],a:3},
  {q:"Cuando un mexicano-americano domiciliado en Estados Unidos solicita protección al consulado de México se aplicará la legislación:",o:["Mexicana.","Estadounidense.","De un tercer Estado.","Del lugar en el que nació (jus soli)."],a:1},
  {q:"El programa Deferred Action for Childhood Arrival (DACA) del Presidente Obama favorece a:",o:["Personas indocumentadas que llegaron a Estados Unidos antes de cumplir 16 años y han vivido allí de manera permanente por lo menos 5 años antes de 2012.","Personas indocumentadas que llegaron a Estados Unidos antes de cumplir 21 años y han vivido allí de manera permanente por lo menos 5 años antes de 2012.","Padres indocumentados de ciudadanos y residentes en Estados Unidos que han vivido allí de manera permanente por lo menos 5 años antes de 2012.","Personas indocumentadas que pertenecen a un grupo restringido de nacionalidades que llegaron a Estados Unidos antes de cumplir 16 años y han vivido allí de manera permanente por lo menos 5 años antes de 2012."],a:0},
  {q:"El poder general amplísimo que se confiere en los consulados para pleitos y cobranzas, así como para la administración de bienes y actos de dominio, se puede otorgar a:",o:["Personas físicas y morales residentes en el extranjero para surtir efectos en la circunscripción consular.","Solamente a diplomáticos extranjeros para surtir efectos en territorio nacional.","Personas físicas y morales que deseen establecer negocios en el extranjero.","Personas físicas y morales que se encuentren en el extranjero para surtir efectos en territorio nacional."],a:3},
  {q:"Las fuentes del derecho consular mexicano son:",o:["Políticas, comerciales, judiciales y marítimas.","Formales, informales, reales e históricas.","Tratados internacionales, legislación local y jurisprudencia.","Práctica, guías, manuales, reciprocidad."],a:2},
  {q:"Tienen derecho a ostentar un pasaporte diplomático mexicano, entre otros:",o:["Empleados locales de las representaciones en el exterior, miembros de la rama técnico-administrativa del Servicio Exterior Mexicano y su familia directa, agentes aduanales y jueces en comisión oficial.","Senadores y diputados al Congreso de la Unión, consejeros de la Judicatura Federal, coordinadores administrativos del Servicio Exterior Mexicano y su familia directa.","Gobernadores de los estados y Jefe de Gobierno de la Ciudad de México, ministros de la Suprema Corte de Justicia de la Nación, miembros de la rama diplomático-consular del Servicio Exterior Mexicano y ex presidentes de la República.","Magistrados en comisión oficial, titulares de entidades paraestatales federales, directores generales o superiores de las demás dependencias federales."],a:2},
  {q:"Las representaciones consulares están facultadas para realizar las siguientes funciones del registro civil:",o:["Divorcio, declaración de ausencia, emancipación de mexicanos y copias certificadas de los mismos.","Matrimonio, nacimiento, defunción de mexicanos y copias certificadas de los mismos.","Reconocimiento de hijos, adopción, tutela de mexicanos y copias certificadas de los mismos.","Testamento, presunción de muerte, pérdida de capacidad legal para administrar bienes de mexicanos y copias certificadas de los mismos."],a:1},
  {q:"El “corte de efectos” es un ______ que los consulados mexicanos deben realizar ______ para reportar las ______ expedidas y canceladas, así como las que quedan para ser utilizadas durante el siguiente mes.",o:["Reporte, semestralmente, etiquetas numeradas.","Informe, anualmente, matrículas numeradas.","Guía, bimestralmente, visas numeradas.","Balance, mensualmente, formas numeradas."],a:3},
  {q:"La función notarial consular incluye los siguientes actos jurídicos, entre otros:",o:["Notificaciones, interpelaciones y requerimientos.","Expedición de poderes, testamentos públicos abiertos y repudio de derechos hereditarios.","Protestas, contratos y entregas de documentos.","Expedición de poderes, hechos jurídicos, convenio de ejercicio de patria potestad e identificación de personas."],a:1},
  {q:"El sistema de inmigración estadounidense se basa en la Ley de Inmigración y Naturalización (INA), las decisiones del Congreso y del Presidente, en principios, preferencias y cuotas anuales. Algunos de sus criterios para otorgar visas de inmigrante son:",o:["Trabajadores agrícolas, mujeres en condición de vulnerabilidad, menores no acompañados.","Reunificación de la familia, protección de refugiados, inmigrantes calificados valiosos para la economía del país.","Inmigrantes que han prestado sus servicios en el ejército y la marina, apátridas, perseguidos políticos.","Representantes de culto, periodistas, trabajadores de la construcción."],a:1},
  {q:"El Servicio de Inmigración y Ciudadanía de Estados Unidos tiene un paquete de visas de no inmigrante que otorga a trabajadores temporales de acuerdo con las leyes de la oferta y la demanda. Algunas de estas visas son:",o:["E1, E3.","J1, J2.","H2A, H2B.","A1, A2."],a:2},
  {q:"Estado de los Estados Unidos de América que cuenta con el número más grande de inmigrantes mexicanos:",o:["Texas.","Arizona.","California.","Nuevo México."],a:2},
  {q:"Los resultados del Censo de Población de 2010 de Estados Unidos indican que la población de origen hispano o latino en ese país pasó de ______ en 2000 a ______ en 2010; de los cuales ______ son mexicanos. La población de origen mexicano se incrementó a ______ durante ese periodo.",o:["20 millones, 40 millones, 15 millones, 25 millones.","25 millones, 42 millones, 18 millones, 28 millones.","35 millones, 50 millones, 11 millones, 32 millones.","32 millones, 54 millones, 14 millones, 35 millones."],a:2},
  {q:"Año en que se adoptó la Declaración Universal de Derechos Humanos:",o:["1945.","1948.","1952.","1966."],a:1},
  {q:"El llamado Programa Bracero entre México y los Estados Unidos de América se estableció por primera vez en ______ y concluyó en ______. Este Programa surgió como consecuencia de la ______ y la falta de mano de obra para trabajar principalmente en el sector ______ estadounidense.",o:["1914, 1918, Primera Guerra Mundial, ferroviario.","1943, 1964, Segunda Guerra Mundial, agrícola.","1950, 1953, Guerra de Corea, de la construcción.","1964, 1975, Guerra de Vietnam, textil."],a:1},
  {q:"En Estados Unidos, la Ley sobre la Reforma a la Inmigración Indocumentada y la Responsabilidad de los Inmigrantes de 1996, que incluía mayores recursos a la patrulla fronteriza, sanciones a empleadores, límites a los derechos de las personas indocumentadas y menos discrecionalidad a la autoridad migratoria, tuvo su origen en la:",o:["Ley Simpson-Rodino.","Proposición 187.","Ley Arizona SB 1070.","Ley Georgia HB87."],a:1},
  {q:"De acuerdo con el artículo 65 del Reglamento de la Ley del Servicio Exterior Mexicano, la asistencia consular consiste en:",o:["Expedir a los mexicanos certificados de matrícula, pasaportes, actas del registro civil y poderes notariales.","Otorgar a los mexicanos constancias de residencia, visados en documentos, certificados de no antecedentes penales, cartillas de servicio militar.","Asesorar a los mexicanos sobre sus derechos y obligaciones frente al Estado receptor, así como asesorar jurídicamente y visitar a los detenidos, enfermos y presos.","Apoyar a los mexicanos que residan en la circunscripción consular con programas de salud, educación, inclusión financiera, actividades deportivas."],a:2},
  {q:"Los objetivos del Programa de Asistencia Jurídica a Mexicanos Sentenciados a Pena de Muerte son los siguientes, EXCEPTO:",o:["Lograr la suspensión de la ejecución de un connacional ya sentenciado a pena de muerte.","Evitar que los mexicanos acusados de delitos punibles por la pena capital reciban dicha sentencia.","Conseguir la extradición a México de un connacional sentenciado a la pena capital.","Lograr la anulación de la sentencia de pena de muerte y la reposición de los procedimientos jurídicos."],a:2},
  {q:"El caso Avena, por el cual México demandó a Estados Unidos ante la Corte Internacional de Justicia en 2003, se refirió a:",o:["Mexicanos cuyos derechos laborales fueron violados por los patrones y no tuvieron acceso a una retribución justa por su condición de indocumentados.","Mexicanos que, teniendo posibilidades de acuerdo con la legislación migratoria de los Estados Unidos de América de permanecer y trabajar en ese país, fueron deportados sin tener acceso a un juez de migración.","Mexicanos que fueron retenidos como esclavos y violados sus derechos humanos en granjas y plantaciones de avena de Estados Unidos de América sin tener acceso a la protección consular y asesoría legal para recobrar su libertad y salarios devengados.","Mexicanos que fueron arrestados en los Estados Unidos de América por la presunta comisión de delitos graves, sin tener acceso a la protección consular, y que fueron sentenciados a la pena de muerte en violación de las garantías del debido proceso legal."],a:3},
  {q:"El Estado mexicano ha utilizado la figura jurídica “amigo de la Corte” en:",o:["Demandas contra leyes antiinmigrantes en Estados Unidos.","Asuntos ante la Corte Europea de Derechos Humanos.","Asuntos ante la Corte Penal Internacional.","Asuntos ante la Suprema Corte de Justicia de la Nación."],a:0},
  {q:"Se encuentran entre las principales organizaciones civiles que trabajan para la promoción y defensa de los derechos de la población hispana en Estados Unidos:",o:["Fundación Ford, Centro Internacional Woodrow Wilson y Sociedad Nacional de MBA Hispanos.","Centro de Investigación Pew, Cámara de Comercio Hispana y la Federación de Migrantes Guillermo de la Rosa Fuentes.","Consejo Nacional de la Raza (NCLR), Fondo Mexicano-Americano de Educación y Defensa Legal (MALDEF) y Liga de Ciudadanos Latinoamericanos Unidos (LULAC).","Consejo de Asuntos Internacionales de Nueva York, Fundación Humberto Mendiola Torres y Club de Migrantes Loma Larga."],a:2},
  {q:"El Programa de Trabajadores Agrícolas Temporales con Canadá (PTAT) incluye una serie de derechos como:",o:["Vivienda, educación y prestaciones familiares.","Cobertura de salud, ausencias por paternidad y enfermedad y acumulación de derechos de pensión.","Seguridad social, vivienda y reunificación familiar.","Vivienda, acumulación de derechos de pensión y reunificación familiar."],a:1},
  {q:"País de América Latina en el que reside la más importante comunidad mexicana de menonitas a la cual se ha brindado asistencia y protección consular:",o:["Colombia.","Bolivia.","Argentina.","Perú."],a:1},
  {q:"Año en el cual México solicitó a la Corte Interamericana de Derechos Humanos una Opinión Consultiva sobre los derechos de los trabajadores migrantes:",o:["1986.","1998.","2002.","2010."],a:2},
  {q:"De acuerdo con el artículo 2 de la Convención Internacional sobre Protección de los Derechos de todos los Trabajadores Migratorios y de sus Familiares se entiende por “trabajadores con empleo concreto” aquel que:",o:["Haya sido enviado por su empleador por un plazo no limitado e indefinido a un Estado de empleo para realizar una tarea o función concreta.","Haya sido enviado por su empleador por un plazo limitado y definido a un Estado de empleo para realizar cualquier tarea.","Realice, por un plazo ilimitado y no definido, un trabajo que requiera conocimientos generales.","Haya sido enviado por su empleador por un plazo limitado y definido a un Estado de empleo para realizar una tarea o función concreta."],a:3}
];

let answered = new Array(questions.length).fill(false);

const container = document.getElementById("quizContainer");
questions.forEach((item, qi) => {
  const div = document.createElement("div");
  div.className = "question";
  div.innerHTML = `<div class="qtext"><span class="qnum">${qi + 1}.</span>${item.q}</div>
    <div class="options" id="opts-${qi}"></div>`;
  container.appendChild(div);

  const opts = div.querySelector(`#opts-${qi}`);
  item.o.forEach((optText, oi) => {
    const btn = document.createElement("button");
    btn.className = "option";
    btn.textContent = String.fromCharCode(97 + oi) + ") " + optText;
    btn.onclick = () => selectAnswer(qi, oi, btn);
    opts.appendChild(btn);
  });
});

function selectAnswer(qi, oi, btn) {
  if (answered[qi]) return;
  answered[qi] = true;
  const opts = document.getElementById(`opts-${qi}`).children;
  const correctIdx = questions[qi].a;
  for (let i = 0; i < opts.length; i++) {
    opts[i].disabled = true;
    if (i === correctIdx) opts[i].classList.add(i === oi ? "correct" : "reveal");
  }
  if (oi !== correctIdx) btn.classList.add("incorrect");
  updateProgress();
}

function updateProgress() {
  const count = answered.filter(Boolean).length;
  document.getElementById("progressFill").style.width = (count / questions.length * 100) + "%";
  document.getElementById("progressText").textContent = `${count} / ${questions.length} respondidas`;
}

document.getElementById("finishBtn").onclick = () => {
  let correct = 0;
  questions.forEach((item, qi) => {
    const opts = document.getElementById(`opts-${qi}`).children;
    if (opts[item.a].classList.contains("correct")) correct++;
  });
  const total = questions.length;
  const answeredCount = answered.filter(Boolean).length;
  const pct = (correct / total * 100).toFixed(1);
  document.getElementById("scoreBig").textContent = pct + "%";
  document.getElementById("scoreDetail").textContent = `${correct} de ${total} correctas · ${answeredCount} de ${total} respondidas`;
  document.getElementById("resultBox").style.display = "block";
  document.getElementById("resultBox").scrollIntoView({behavior: "smooth"});
};

document.getElementById("retryBtn").onclick = () => location.reload();
